# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 500)
        MainWindow.setStyleSheet("background-color: rgb(166, 208, 218);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(340, 0, 16, 561))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.welcome_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(30, 20, 291, 81))
        self.welcome_label.setObjectName("welcome_label")
        self.welcome_label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.welcome_label2.setGeometry(QtCore.QRect(90, 90, 171, 41))
        self.welcome_label2.setObjectName("welcome_label2")
        self.input_edit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.input_edit.setGeometry(QtCore.QRect(40, 140, 281, 61))
        self.input_edit.setStyleSheet("background-color: rgb(232, 233, 243);")
        self.input_edit.setObjectName("input_edit")
        self.time_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(30, 210, 81, 41))
        self.time_label.setObjectName("time_label")
        self.priority_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.priority_label.setGeometry(QtCore.QRect(50, 280, 111, 31))
        self.priority_label.setObjectName("priority_label")
        self.radio_high = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_high.setGeometry(QtCore.QRect(200, 270, 62, 14))
        self.radio_high.setObjectName("radio_high")
        self.radio_medium = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_medium.setGeometry(QtCore.QRect(200, 290, 62, 14))
        self.radio_medium.setObjectName("radio_medium")
        self.radio_low = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_low.setGeometry(QtCore.QRect(200, 310, 62, 14))
        self.radio_low.setObjectName("radio_low")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(130, 340, 81, 31))
        self.submit_button.setStyleSheet("background-color: rgb(232, 233, 243);")
        self.submit_button.setObjectName("submit_button")
        self.date_time_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.date_time_label.setGeometry(QtCore.QRect(90, 390, 211, 41))
        self.date_time_label.setStyleSheet("")
        self.date_time_label.setObjectName("date_time_label")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(120, 220, 101, 22))
        self.dateEdit.setStyleSheet("background-color: rgb(232, 233, 243);")
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(230, 220, 101, 22))
        self.timeEdit.setStyleSheet("background-color: rgb(232, 233, 243);")
        self.timeEdit.setObjectName("timeEdit")
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(75, 380, 231, 20))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(370, 10, 431, 451))
        self.listWidget.setStyleSheet("background-color: rgb(232, 233, 243);")
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Hello, </span></p><p align=\"center\"><span style=\" font-size:16pt;\">Welcome to your To-Do List</span></p></body></html>"))
        self.welcome_label2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">What needs done?</span></p></body></html>"))
        self.time_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">By when?</span></p></body></html>"))
        self.priority_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Priority Level:</span></p></body></html>"))
        self.radio_high.setText(_translate("MainWindow", "High"))
        self.radio_medium.setText(_translate("MainWindow", "Medium"))
        self.radio_low.setText(_translate("MainWindow", "Low"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.date_time_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Today is: (Date and Time here)</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
